setwd("D:/METOPEL/UAS METOPEL")
install.packages("readxl")
library("readxl")
install.packages("tidyerves")
library(tidyverse)
install.packages("WDI")
library("WDI")
grace<-read_excel('latihan.xlsx')
reg<-lm(Y~X,data=grace)
summary(reg)
